[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && node dist/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
